name: uniplan_models
description: Shared DTOs for UniPlan frontend and E2E tests
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.4.7
  json_serializable: ^6.9.0
